/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quizz2.view;

/**
 *
 * @author Usuario
 */
public class GUICotizacion extends javax.swing.JFrame {

    /**
     * Creates new form GUICotizacion
     */
    public GUICotizacion() {
        initComponents();
    }

    public DataPanelBotones getDataPanelBotones1() {
        return dataPanelBotones1;
    }

    public DataPanelCotizacion getDataPanelCotizacion1() {
        return dataPanelCotizacion1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataPanelBotones1 = new com.mycompany.quizz2.view.DataPanelBotones();
        dataPanelCotizacion1 = new com.mycompany.quizz2.view.DataPanelCotizacion();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(dataPanelBotones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 510, 110));
        getContentPane().add(dataPanelCotizacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.quizz2.view.DataPanelBotones dataPanelBotones1;
    private com.mycompany.quizz2.view.DataPanelCotizacion dataPanelCotizacion1;
    // End of variables declaration//GEN-END:variables
}
